use std::fs;
use std::path::Path;

/// Writes `public/sidex-env.js` with the host platform resolved from the
/// Cargo target triple (`CARGO_CFG_TARGET_*` env vars set by Cargo for build
/// scripts). Unlike browser-side detection (`navigator.userAgent`, WebGL
/// renderer probing) these are compile-time constants that always match the
/// SideX binary, so the webview gets the authoritative `__SIDEX_ARCH__` /
/// `__SIDEX_OS__` / `__SIDEX_TARGET_PLATFORM__` before any other script runs.
///
/// This is the root fix for extensions being installed for the wrong
/// platform (e.g. `linux-x64` on macOS): the frontend reads these globals to
/// compute `CURRENT_TARGET_PLATFORM`, and the Rust `ensure_target_platform`
/// fallback also keys off `current_target_platform()` derived from the same
/// `cfg!` constants.
fn write_sidex_env() {
    let arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    let arch_js = match arch.as_str() {
        "aarch64" => "arm64",
        "x86_64" => "x64",
        "x86" => "x86",
        other => {
            eprintln!(
                "cargo:warning=unknown CARGO_CFG_TARGET_ARCH={other}, falling back to x64 in sidex-env.js"
            );
            "x64"
        }
    };
    let os_js = match os.as_str() {
        "macos" => "darwin",
        "windows" => "win32",
        "linux" => "linux",
        other => {
            eprintln!(
                "cargo:warning=unknown CARGO_CFG_TARGET_OS={other}, falling back to linux in sidex-env.js"
            );
            "linux"
        }
    };
    let target = format!("{os_js}-{arch_js}");

    let content = format!(
        "// Auto-generated by src-tauri/build.rs from CARGO_CFG_TARGET_*.\n\
         // Do not edit - regenerated on every cargo build. Provides the host\n\
         // platform to the webview before any other script runs, so the\n\
         // frontend targetPlatform detection matches the SideX binary.\n\
         globalThis.__SIDEX_TAURI__ = true;\n\
         globalThis.__SIDEX_ARCH__ = {arch_js:?};\n\
         globalThis.__SIDEX_OS__ = {os_js:?};\n\
         globalThis.__SIDEX_TARGET_PLATFORM__ = {target:?};\n"
    );

    let dst = Path::new("../public/sidex-env.js");
    // Only rewrite when content changed so Vite doesn't reload on every build.
    let needs_write = fs::read(dst).map_or(true, |existing| existing != content.as_bytes());
    if needs_write {
        if let Err(e) = fs::write(dst, &content) {
            eprintln!("cargo:warning=failed to write public/sidex-env.js: {e}");
        }
    }
}

fn main() {
    write_sidex_env();

    let scripts_src = Path::new("../src/vs/workbench/contrib/terminal/common/scripts");
    let scripts_dst = Path::new("shell-integration");

    if scripts_src.exists() {
        fs::create_dir_all(scripts_dst).expect("Failed to create shell-integration dir");

        let shell_files = [
            "shellIntegration-rc.zsh",
            "shellIntegration-env.zsh",
            "shellIntegration-profile.zsh",
            "shellIntegration-login.zsh",
            "shellIntegration-bash.sh",
            "shellIntegration.fish",
            "shellIntegration.ps1",
        ];

        for file in &shell_files {
            let src = scripts_src.join(file);
            let dst = scripts_dst.join(file);
            if src.exists() {
                let src_bytes =
                    fs::read(&src).unwrap_or_else(|e| panic!("Failed to read {file}: {e}"));
                let needs_copy = fs::read(&dst).map_or(true, |dst_bytes| dst_bytes != src_bytes);
                if needs_copy {
                    fs::write(&dst, &src_bytes)
                        .unwrap_or_else(|e| panic!("Failed to copy {file}: {e}"));
                }
                println!("cargo:rerun-if-changed={}", src.display());
            }
        }
    }

    let ext_host_src = Path::new("extension-host");
    let ext_host_targets = [
        Path::new("target/debug/extension-host"),
        Path::new("target/release/extension-host"),
    ];
    if ext_host_src.exists() {
        for ext_host_dst in &ext_host_targets {
            fs::create_dir_all(ext_host_dst).ok();
            for file in &["server.cjs", "host.cjs"] {
                let src = ext_host_src.join(file);
                let dst = ext_host_dst.join(file);
                if src.exists() {
                    let src_bytes = fs::read(&src).unwrap_or_default();
                    let needs_copy =
                        fs::read(&dst).map_or(true, |dst_bytes| dst_bytes != src_bytes);
                    if needs_copy {
                        let _ = fs::write(&dst, &src_bytes);
                    }
                }
            }
        }
        for file in &["server.cjs", "host.cjs"] {
            let src = ext_host_src.join(file);
            if src.exists() {
                println!("cargo:rerun-if-changed={}", src.display());
            }
        }
    }

    tauri_build::build();
}
